# GitRepo resource to register this repository with Fleet
# Apply this to your Fleet management cluster
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kubeflow
  namespace: fleet-default
spec:
  # Update this to your Git repository URL
  repo: https://github.com/stevenbecht/kubeflow-fleet
  branch: v1.11.0up

  # Paths to scan for bundles (order doesn't matter - Fleet uses dependsOn)
  paths:
  # Infrastructure
  - cert-manager
  - istio-system
  - istiod
  - istio-gateway
  # Kubeflow components
  - kubeflow-namespace
  - kubeflow-base
  - kubeflow-dex
  - kubeflow-oauth2-proxy
  - kubeflow-prometheus-stack
  - kubeflow-crds
  - kubeflow-admission-webhook
  - kubeflow-profiles
  - kubeflow-user-namespace
  - kubeflow-central-dashboard
  - kubeflow-pipelines
  - kubeflow-notebooks
  - kubeflow-tensorboards
  - kubeflow-katib
  - kubeflow-training-operator
  - kubeflow-knative-crds
  - kubeflow-knative
  - kubeflow-serving
  - kubeflow-spark-operator

  # Target clusters with kubeflow=enabled label
  targets:
  - name: kubeflow-clusters
    clusterSelector:
      matchLabels:
        kubeflow: enabled

  # Polling interval
  pollingInterval: 5m

  # Optional: specify client secret for private repos
  # clientSecretName: git-credentials
