# InferenceService CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inferenceservices.serving.kserve.io
spec:
  group: serving.kserve.io
  names:
    kind: InferenceService
    listKind: InferenceServiceList
    plural: inferenceservices
    singular: inferenceservice
    shortNames:
    - isvc
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: URL
      type: string
      jsonPath: .status.url
    - name: Ready
      type: string
      jsonPath: .status.conditions[?(@.type=='Ready')].status
    - name: Prev
      type: integer
      jsonPath: .status.components.predictor.previousRolledoutRevision
    - name: Latest
      type: integer
      jsonPath: .status.components.predictor.latestRolledoutRevision
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
---
# TrainedModel CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trainedmodels.serving.kserve.io
spec:
  group: serving.kserve.io
  names:
    kind: TrainedModel
    listKind: TrainedModelList
    plural: trainedmodels
    singular: trainedmodel
    shortNames:
    - tm
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
# InferenceGraph CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inferencegraphs.serving.kserve.io
spec:
  group: serving.kserve.io
  names:
    kind: InferenceGraph
    listKind: InferenceGraphList
    plural: inferencegraphs
    singular: inferencegraph
    shortNames:
    - ig
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
# ClusterServingRuntime CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterservingruntimes.serving.kserve.io
spec:
  group: serving.kserve.io
  names:
    kind: ClusterServingRuntime
    listKind: ClusterServingRuntimeList
    plural: clusterservingruntimes
    singular: clusterservingruntime
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
# ServingRuntime CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servingruntimes.serving.kserve.io
spec:
  group: serving.kserve.io
  names:
    kind: ServingRuntime
    listKind: ServingRuntimeList
    plural: servingruntimes
    singular: servingruntime
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
