# TFJob CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tfjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: TFJob
    listKind: TFJobList
    plural: tfjobs
    singular: tfjob
    shortNames:
    - tf
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: State
      type: string
      jsonPath: .status.conditions[-1:].type
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
---
# PyTorchJob CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pytorchjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: PyTorchJob
    listKind: PyTorchJobList
    plural: pytorchjobs
    singular: pytorchjob
    shortNames:
    - pytj
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: State
      type: string
      jsonPath: .status.conditions[-1:].type
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
---
# MPIJob CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: MPIJob
    listKind: MPIJobList
    plural: mpijobs
    singular: mpijob
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: State
      type: string
      jsonPath: .status.conditions[-1:].type
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  - name: v2beta1
    served: true
    storage: false
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
# XGBoostJob CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: xgboostjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: XGBoostJob
    listKind: XGBoostJobList
    plural: xgboostjobs
    singular: xgboostjob
    shortNames:
    - xgbj
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: State
      type: string
      jsonPath: .status.conditions[-1:].type
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
---
# PaddleJob CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: paddlejobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: PaddleJob
    listKind: PaddleJobList
    plural: paddlejobs
    singular: paddlejob
    shortNames:
    - pdj
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: State
      type: string
      jsonPath: .status.conditions[-1:].type
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
---
# JAXJob CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jaxjobs.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: JAXJob
    listKind: JAXJobList
    plural: jaxjobs
    singular: jaxjob
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: State
      type: string
      jsonPath: .status.conditions[-1:].type
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
