apiVersion: batch/v1
kind: Job
metadata:
  generateName: storage-version-migration-serving-
  labels:
    app: storage-version-migration-serving
    app.kubernetes.io/component: storage-version-migration-job
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.16.2
  name: storage-version-migration-serving
  namespace: knative-serving
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: storage-version-migration-serving
        app.kubernetes.io/component: storage-version-migration-job
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/version: 1.16.2
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - args:
        - services.serving.knative.dev
        - configurations.serving.knative.dev
        - revisions.serving.knative.dev
        - routes.serving.knative.dev
        - domainmappings.serving.knative.dev
        image: gcr.io/knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:1b09bcf7e7304c400780d370c25702bf1c26291d9e431bfb3d553c4ce71b0c97
        name: migrate
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: OnFailure
      serviceAccountName: controller
